<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="api-a"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://ws.spring.monichev.com/api-a"
                  xmlns:types="http://ws.spring.monichev.com/api-a/types"
                  xmlns:common="http://ws.spring.monichev.com/common/types"
                  targetNamespace="http://ws.spring.monichev.com/api-a">

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    targetNamespace="http://ws.spring.monichev.com/api-a/types"
                    elementFormDefault="qualified">
            <xsd:include schemaLocation="api-a.xsd"/>

            <xsd:element name="getTypeAList">
                <xsd:complexType/>
            </xsd:element>
            <xsd:element name="getTypeAListResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="typeAList" type="types:typeA" minOccurs="0" maxOccurs="unbounded">
                            <xsd:annotation>
                                <xsd:documentation>List of all type A objects</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="getTypeAListRequest">
        <wsdl:part name="parameters" element="types:getTypeAList"/>
    </wsdl:message>
    <wsdl:message name="getTypeAListResponse">
        <wsdl:part name="parameters" element="types:getTypeAListResponse"/>
    </wsdl:message>

    <wsdl:portType name="apiA">
        <wsdl:operation name="getTypeAList">
            <wsdl:documentation>Get a list of all Type A objects</wsdl:documentation>
            <wsdl:input message="tns:getTypeAListRequest"/>
            <wsdl:output message="tns:getTypeAListResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="apiABinding" type="tns:apiA">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getTypeAList">
            <soap:operation soapAction="http://ws.spring.monichev.com/api-a/getTypeAs"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="ApiAImpl">
        <wsdl:documentation>API A Service</wsdl:documentation>
        <wsdl:port name="apiAPort" binding="tns:apiABinding">
            <soap:address location="http://localhost:8080/spring-ws/api-a.wsdl"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
