<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="api-ext"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://ws.spring.monichev.com/api-ext"
                  xmlns:types="http://ws.spring.monichev.com/api-ext/types"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="http://ws.spring.monichev.com/api-ext">

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    targetNamespace="http://ws.spring.monichev.com/api-ext/types"
                    elementFormDefault="qualified">
            <xsd:include schemaLocation="api-ext-types.xsd"/>

            <xsd:element name="getTypeExtList">
                <xsd:complexType/>
            </xsd:element>
            <xsd:element name="getTypeExtListResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="TypeExtList" type="types:typeExt" minOccurs="0" maxOccurs="unbounded">
                            <xsd:annotation>
                                <xsd:documentation>List of all type Ext objects</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="getTypeExtListRequest">
        <wsdl:part name="parameters" element="types:getTypeExtList"/>
    </wsdl:message>
    <wsdl:message name="getTypeExtListResponse">
        <wsdl:part name="parameters" element="types:getTypeExtListResponse"/>
    </wsdl:message>

    <wsdl:portType name="apiExt">
        <wsdl:operation name="getTypeExtList">
            <wsdl:documentation>Get a list of all Type Ext objects</wsdl:documentation>
            <wsdl:input message="tns:getTypeExtListRequest"/>
            <wsdl:output message="tns:getTypeExtListResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="apiExtBinding" type="tns:apiExt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getTypeExtList">
            <soap:operation soapAction="http://ws.spring.monichev.com/api-ext/getTypeAs"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="apiExtImpl">
        <wsdl:documentation>API Ext Service</wsdl:documentation>
        <wsdl:port name="apiExtPort" binding="tns:apiExtBinding">
            <soap:address location="http://localhost:8080/spring-ws/api-ext.wsdl"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
